### ISSUE TITLE
Make RequestPerRoute Lumen compatible

### ISSUE THREAD

**Issue by MyIgel** [triadev/LaravelPrometheusExporter#11]
Imho this should be a only a small change:
Instead of using
```php
$route = Route::currentRouteName() ?: 'unnamed';
```
it should be
```php
$route = $request->path();
```
if running in an Lumen environment

**Comment by triadev** [comment]
I wrote in the readme: "RequestPerRoute (only laravel)"
But I think it's a good idea an I'm going to make the middleware Lumen compatible!
