### ISSUE TITLE
How to use it with Lumen?

### ISSUE THREAD

**Issue by MyIgel** [triadev/LaravelPrometheusExporter#9]
The `PrometheusExporterController extends Illuminate\Routing\Controller` which is not available in Lumen

**Comment by triadev** [comment]
Thank you very much for your question! With the next update at this evening the controller for lumen will be available.

**Comment by triadev** [comment]
The new version is ready!

When you are using lumen you must register the route on your own. Here is an example:

Route::get(
    ROUTE,
    \Triadev\PrometheusExporter\Controller\LumenController::class . '@metrics'
);
